version: 2
jobs:
    build:
        docker:
            - image: philomath213/gef-legacy:latest
        working_directory: ~/repo
        steps:
            - checkout
            - run: make lint
            - run: make test
